### ISSUE TITLE
Google Style Emoji?

### ISSUE THREAD

**Issue by LinkofHyrule89** [locomojis/Chromoji#40] opened 2013-09-24 20:18 UTC
It would be awesome if you could add in an option to use the new Google Style Emoji from Hangouts instead of the Mac ones. This images shows some of them but I'm sure you can get the individual images from the hangouts app. http://www.cypressnorth.com/wp-content/uploads/2013/05/Google-Hangout-Emojis.jpg

**Comment by RobJDavey** [comment] 2014-01-31 10:10
Duplicate of #35

**Closed as completed by RobJDavey** 2014-01-31 10:10 UTC
Labels: duplicate
