### ISSUE TITLE
Android Emoji

### ISSUE THREAD

**Issue by PushkaCom** [locomojis/Chromoji#43] opened 2013-12-06 05:46 UTC
Hi ~ not really an issue (I love the extension!) ~ 
finally a good one 

But I would love it all the more if it had android emoji like this extension:
http://u.pushka.co/1dTNRGL

<3 <3

**Comment by RobJDavey** [comment] 2014-01-31 10:06
Duplicate of #40

**Closed as completed by RobJDavey** 2014-01-31 10:06 UTC
Labels: duplicate
