### ISSUE TITLE
Chromoji Breaks Webflow.com

### ISSUE THREAD

**Issue by cdes** [locomojis/Chromoji#56] opened 2014-02-12 08:27 UTC
As the titles says.

I'm using webflow, and I've noticed that Chromoji doesn't allow webflow to load css.
You can try webflow, they have a free plan.

**Comment by locomojis** [comment] 2014-02-15 01:39
I'll definitely take a look. Thanks!

**Comment by locomojis** [comment] 2014-02-15 12:57
The problem can be traced back to these lines:

```
var css = document.createElement('style');
css.innerHTML = 'img.chromoji { ... }';
document.body.appendChild(css);
```

Perhaps webflow is using/manipulating the last `<style>` element inside the `<body>`.

If I use `<head>`, it works fine. This will be included in the new version as a fix, 
but I reached out to the webflow guys to get some input why this is happening.

**Comment by callmevlad** [comment] 2014-02-16 04:01
Hi guys, I work on Webflow and am not able to reproduce any errors once I install this extension. I've tried on Chrome Stable as well as Canary, and the editor seems to work fine.

Also, as far as I can recall, the HTML4 and HTML5 specs do not allow `<style>` tags in the `<body>` - they should only be in the `<head>`. I checked all of our stylesheet code, and we don't have any that tries to find/manipulate style elements inside the body.

However, Webflow _does_ try to parse all elements inside the editor's iframe, so I can see how adding a `<style>` tag to the `<body>` inside the iframe would trip up Webflow while trying to save the DOM tree.

**Comment by locomojis** [comment] 2014-02-16 07:45
Hi Vlad! I also sent you an email. While `<style>` inside the `<body>` may not be according to the spec, it works in all browsers as far as I can tell, and for an extension like this one it's important to be the last stylesheet in order not to be overwritten by some other style on the page.

I updated the ext to inject inside `<head>` for now, but my suggested fix on your end is to use `StyleSheet.ownerNode` with a unique ID on your `<style>` element to find the stylesheet you injected.

I should say it's IE9+ but for an editor like yours I don't think you support anything below that. :)

**Comment by locomojis** [comment] 2014-02-16 08:39
Vlad was kind enough to include the suggested fix.

(and I'll be injecting to the `<head>` until there's a user report
about my extension not working properly :-)

In the meantime I consider this as fixed.

**Closed as completed by locomojis** 2014-02-16 08:39 UTC
Labels: bug

**Comment by cdes** [comment] 2014-02-16 08:48
Wow, thanks guys :+1:
